### ISSUE TITLE
create students#identifiers

### ISSUE THREAD

**Issue by almartin82** [TEAMSchools/mandi#1]
a convenience view, which:
-joins to custom to get key custom fields (SPED etc)
-joins to cohort to get cohort name
-has a use for reporting flag that takes into account enroll status and out of district

**Comment by cbini** [comment]
bruh

https://github.com/TEAMSchools/mandi/blob/master/COHORT/v_COHORT%24identifiers_long.sql
https://github.com/TEAMSchools/mandi/blob/master/COHORT/v_COHORT%24identifiers_scaffold.sql
